# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fa4d2b7796a0a7813fddca407ee37bbb66d58d57380a9a0335a8ef6ed9ae45ad260e3478a9777c071cabde4ffe113649245ca911d39f98b7eb0189bae84b44a

test:
  secret_key_base: bac879163d01f5f20b6db103bebf736fd0615fc91f1c0d0e8b3ec998625c99a172b07ec26368734cbb94bdb6102b365e982bbab5b08c94f0b38ac27daef7e17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
